// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Pizzeria.Pos.Data;

#nullable disable

namespace Pizzeria.Pos.Data.Migrations
{
    [DbContext(typeof(PosDataContext))]
    [Migration("20260328122943_nowe-adresy")]
    partial class noweadresy
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.10");

            modelBuilder.Entity("Pizzeria.Pos.Core.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .HasColumnType("TEXT");

                    b.Property<string>("ApartmentNumber")
                        .HasColumnType("TEXT");

                    b.Property<string>("City")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomerName")
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomerPhone")
                        .HasColumnType("TEXT");

                    b.Property<string>("DeliveryApartmentNumber")
                        .HasColumnType("TEXT");

                    b.Property<string>("DeliveryCity")
                        .HasColumnType("TEXT");

                    b.Property<string>("DeliveryHouseNumber")
                        .HasColumnType("TEXT");

                    b.Property<string>("DeliveryPostalCode")
                        .HasColumnType("TEXT");

                    b.Property<string>("DeliveryStreet")
                        .HasColumnType("TEXT");

                    b.Property<string>("DeliverySymbol")
                        .HasColumnType("TEXT");

                    b.Property<string>("HouseNumber")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsCanceled")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsPaid")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<string>("PaymentMethod")
                        .HasColumnType("TEXT");

                    b.Property<string>("PostalCode")
                        .HasColumnType("TEXT");

                    b.Property<string>("Street")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Total")
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("Pizzeria.Pos.Core.Models.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BaseProductName")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("BaseProductPrice")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConfigurationJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<int>("OrderId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("Pizzeria.Pos.Core.Models.PizzaAddonDefinition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("GroupName")
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("PizzaAddonDefinitions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            GroupName = "Ser",
                            IsActive = true,
                            Name = "Extra ser",
                            Price = 6m,
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 2,
                            GroupName = "Ser",
                            IsActive = true,
                            Name = "Mozzarella",
                            Price = 7m,
                            SortOrder = 2
                        },
                        new
                        {
                            Id = 3,
                            GroupName = "Ser",
                            IsActive = true,
                            Name = "Gorgonzola",
                            Price = 8m,
                            SortOrder = 3
                        },
                        new
                        {
                            Id = 4,
                            GroupName = "Ser",
                            IsActive = true,
                            Name = "Parmezan",
                            Price = 7m,
                            SortOrder = 4
                        },
                        new
                        {
                            Id = 5,
                            GroupName = "Ser",
                            IsActive = true,
                            Name = "Ricotta",
                            Price = 8m,
                            SortOrder = 5
                        },
                        new
                        {
                            Id = 6,
                            GroupName = "Mięsne",
                            IsActive = true,
                            Name = "Szynka",
                            Price = 7m,
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 7,
                            GroupName = "Mięsne",
                            IsActive = true,
                            Name = "Salami",
                            Price = 7m,
                            SortOrder = 2
                        },
                        new
                        {
                            Id = 8,
                            GroupName = "Mięsne",
                            IsActive = true,
                            Name = "Boczek",
                            Price = 8m,
                            SortOrder = 3
                        },
                        new
                        {
                            Id = 9,
                            GroupName = "Mięsne",
                            IsActive = true,
                            Name = "Kurczak z grilla",
                            Price = 9m,
                            SortOrder = 4
                        },
                        new
                        {
                            Id = 10,
                            GroupName = "Mięsne",
                            IsActive = true,
                            Name = "Pepperoni",
                            Price = 8m,
                            SortOrder = 5
                        },
                        new
                        {
                            Id = 11,
                            GroupName = "Mięsne",
                            IsActive = true,
                            Name = "Nduja",
                            Price = 9m,
                            SortOrder = 6
                        },
                        new
                        {
                            Id = 12,
                            GroupName = "Mięsne",
                            IsActive = true,
                            Name = "Salsiccia",
                            Price = 9m,
                            SortOrder = 7
                        },
                        new
                        {
                            Id = 13,
                            GroupName = "Warzywne",
                            IsActive = true,
                            Name = "Pieczarki",
                            Price = 5m,
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 14,
                            GroupName = "Warzywne",
                            IsActive = true,
                            Name = "Papryka",
                            Price = 4m,
                            SortOrder = 2
                        },
                        new
                        {
                            Id = 15,
                            GroupName = "Warzywne",
                            IsActive = true,
                            Name = "Cebula",
                            Price = 3m,
                            SortOrder = 3
                        },
                        new
                        {
                            Id = 16,
                            GroupName = "Warzywne",
                            IsActive = true,
                            Name = "Oliwki czarne",
                            Price = 5m,
                            SortOrder = 4
                        },
                        new
                        {
                            Id = 17,
                            GroupName = "Warzywne",
                            IsActive = true,
                            Name = "Oliwki zielone",
                            Price = 5m,
                            SortOrder = 5
                        },
                        new
                        {
                            Id = 18,
                            GroupName = "Warzywne",
                            IsActive = true,
                            Name = "Pomidory suszone",
                            Price = 6m,
                            SortOrder = 6
                        },
                        new
                        {
                            Id = 19,
                            GroupName = "Warzywne",
                            IsActive = true,
                            Name = "Rukola",
                            Price = 4m,
                            SortOrder = 7
                        },
                        new
                        {
                            Id = 20,
                            GroupName = "Warzywne",
                            IsActive = true,
                            Name = "Ananas",
                            Price = 4m,
                            SortOrder = 8
                        },
                        new
                        {
                            Id = 21,
                            GroupName = "Warzywne",
                            IsActive = true,
                            Name = "Szpinak",
                            Price = 4m,
                            SortOrder = 9
                        },
                        new
                        {
                            Id = 22,
                            GroupName = "Warzywne",
                            IsActive = true,
                            Name = "Karczoch",
                            Price = 6m,
                            SortOrder = 10
                        },
                        new
                        {
                            Id = 23,
                            GroupName = "Sosy",
                            IsActive = true,
                            Name = "Sos pomidorowy",
                            Price = 4m,
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 24,
                            GroupName = "Sosy",
                            IsActive = true,
                            Name = "Sos czosnkowy",
                            Price = 4m,
                            SortOrder = 2
                        },
                        new
                        {
                            Id = 25,
                            GroupName = "Sosy",
                            IsActive = true,
                            Name = "Sos BBQ",
                            Price = 4m,
                            SortOrder = 3
                        },
                        new
                        {
                            Id = 26,
                            GroupName = "Sosy",
                            IsActive = true,
                            Name = "Sos ostry",
                            Price = 4m,
                            SortOrder = 4
                        },
                        new
                        {
                            Id = 27,
                            GroupName = "Sosy",
                            IsActive = true,
                            Name = "Pesto",
                            Price = 5m,
                            SortOrder = 5
                        },
                        new
                        {
                            Id = 28,
                            GroupName = "Sosy",
                            IsActive = true,
                            Name = "Sos śmietanowy",
                            Price = 4m,
                            SortOrder = 6
                        });
                });

            modelBuilder.Entity("Pizzeria.Pos.Core.Models.PrintedDocument", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ContentPreview")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DocumentType")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("TEXT");

                    b.Property<string>("JobName")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int?>("OrderId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PrinterName")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<bool>("Success")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("PrintedDocuments");
                });

            modelBuilder.Entity("Pizzeria.Pos.Core.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Pizza",
                            Name = "Margherita",
                            Price = 32m
                        },
                        new
                        {
                            Id = 2,
                            Category = "Pizza",
                            Name = "Pepperoni",
                            Price = 38m
                        },
                        new
                        {
                            Id = 3,
                            Category = "Pizza",
                            Name = "Quattro Formaggi",
                            Price = 42m
                        },
                        new
                        {
                            Id = 4,
                            Category = "Pizza",
                            Name = "Prosciutto",
                            Price = 40m
                        },
                        new
                        {
                            Id = 5,
                            Category = "Pizza",
                            Name = "Diavola",
                            Price = 39m
                        },
                        new
                        {
                            Id = 6,
                            Category = "Pizza",
                            Name = "Hawajska",
                            Price = 37m
                        },
                        new
                        {
                            Id = 7,
                            Category = "Pizza",
                            Name = "Capricciosa",
                            Price = 40m
                        },
                        new
                        {
                            Id = 8,
                            Category = "Pizza",
                            Name = "Vege",
                            Price = 35m
                        },
                        new
                        {
                            Id = 9,
                            Category = "Pizza",
                            Name = "BBQ Kurczak",
                            Price = 41m
                        },
                        new
                        {
                            Id = 10,
                            Category = "Pizza",
                            Name = "Fungi",
                            Price = 36m
                        },
                        new
                        {
                            Id = 11,
                            Category = "Pizza",
                            Name = "Tonno",
                            Price = 39m
                        },
                        new
                        {
                            Id = 12,
                            Category = "Pizza",
                            Name = "Romana",
                            Price = 36m
                        },
                        new
                        {
                            Id = 13,
                            Category = "Pizza",
                            Name = "Calabrese",
                            Price = 41m
                        },
                        new
                        {
                            Id = 14,
                            Category = "Pizza",
                            Name = "Truflowa",
                            Price = 48m
                        },
                        new
                        {
                            Id = 15,
                            Category = "Napoje zimne",
                            Name = "Coca-Cola 0,33l",
                            Price = 7m
                        },
                        new
                        {
                            Id = 16,
                            Category = "Napoje zimne",
                            Name = "Coca-Cola 0,5l",
                            Price = 9m
                        },
                        new
                        {
                            Id = 17,
                            Category = "Napoje zimne",
                            Name = "Sprite 0,33l",
                            Price = 7m
                        },
                        new
                        {
                            Id = 18,
                            Category = "Napoje zimne",
                            Name = "Fanta 0,33l",
                            Price = 7m
                        },
                        new
                        {
                            Id = 19,
                            Category = "Napoje zimne",
                            Name = "Woda niegazowana",
                            Price = 5m
                        },
                        new
                        {
                            Id = 20,
                            Category = "Napoje zimne",
                            Name = "Woda gazowana",
                            Price = 5m
                        },
                        new
                        {
                            Id = 21,
                            Category = "Napoje zimne",
                            Name = "Sok pomarańczowy",
                            Price = 8m
                        },
                        new
                        {
                            Id = 22,
                            Category = "Napoje zimne",
                            Name = "Sok jabłkowy",
                            Price = 8m
                        },
                        new
                        {
                            Id = 23,
                            Category = "Napoje zimne",
                            Name = "Lemońska domowa",
                            Price = 10m
                        },
                        new
                        {
                            Id = 24,
                            Category = "Napoje ciepłe",
                            Name = "Kawa espresso",
                            Price = 8m
                        },
                        new
                        {
                            Id = 25,
                            Category = "Napoje ciepłe",
                            Name = "Cappuccino",
                            Price = 10m
                        },
                        new
                        {
                            Id = 26,
                            Category = "Napoje ciepłe",
                            Name = "Latte macchiato",
                            Price = 11m
                        },
                        new
                        {
                            Id = 27,
                            Category = "Napoje ciepłe",
                            Name = "Herbata",
                            Price = 7m
                        });
                });

            modelBuilder.Entity("Pizzeria.Pos.Core.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Pin")
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsActive = true,
                            Name = "Manager",
                            Pin = "1989",
                            Role = "Manager"
                        },
                        new
                        {
                            Id = 2,
                            IsActive = true,
                            Name = "Kelner1",
                            Pin = "1648",
                            Role = "Kelner"
                        },
                        new
                        {
                            Id = 3,
                            IsActive = true,
                            Name = "Kelner2",
                            Pin = "2211",
                            Role = "Kelner"
                        });
                });

            modelBuilder.Entity("Pizzeria.Pos.Core.Models.Order", b =>
                {
                    b.HasOne("Pizzeria.Pos.Core.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Pizzeria.Pos.Core.Models.OrderItem", b =>
                {
                    b.HasOne("Pizzeria.Pos.Core.Models.Order", "Order")
                        .WithMany("Items")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("Pizzeria.Pos.Core.Models.Order", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
